[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.25'
evm_version = "cancun"
optimizer_runs = 800
via_ir = false
ffi = true

[rpc_endpoints]
sepolia = "https://polygon-mainnet.infura.io/v3/<Polygon_Infura_KEY>"
op_sepolia = "https://mainnet.base.org/"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
